export const contractAddress = "0x000000000001F04A9533e92d7AD4dDe7DC19a8F3";
export const contractAbi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "claimer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "privateKey",
        type: "bytes32",
      },
    ],
    name: "BountyClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "bountyId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "reward",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "publicKey",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "requiredScore",
        type: "uint8",
      },
      { indexed: false, internalType: "uint8", name: "flag", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "locked", type: "uint8" },
    ],
    name: "BountyCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "claimer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "privateKey",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "publicKey",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "address",
        name: "leaderAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "rewardAmount",
        type: "uint256",
      },
    ],
    name: "LeaderClaimed",
    type: "event",
  },
  {
    inputs: [],
    name: "AA",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "BB",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "Leader",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LeaderAddr",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "LeaderPub",
    outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "PP",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "Scry",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "addr", type: "address" },
      { internalType: "uint8", name: "n", type: "uint8" },
    ],
    name: "addressStartsWithNZeroes",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "bounties",
    outputs: [
      { internalType: "uint8", name: "score", type: "uint8" },
      { internalType: "address payable", name: "creator", type: "address" },
      { internalType: "uint256", name: "reward", type: "uint256" },
      { internalType: "bytes", name: "publicKey", type: "bytes" },
      { internalType: "bytes32", name: "privateKey", type: "bytes32" },
      { internalType: "address", name: "addrs", type: "address" },
      { internalType: "uint8", name: "flag", type: "uint8" },
      { internalType: "bytes", name: "custom", type: "bytes" },
      { internalType: "uint8", name: "locked", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "bounty", type: "uint256" },
      { internalType: "bytes32", name: "PK", type: "bytes32" },
    ],
    name: "bounty",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "PK", type: "bytes32" }],
    name: "bountyLeader",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "data", type: "bytes" }],
    name: "bytesToHexString",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "bounty", type: "uint256" },
      { internalType: "bytes32", name: "PK", type: "bytes32" },
    ],
    name: "checkCreate2",
    outputs: [
      { internalType: "bytes20", name: "addrBytes", type: "bytes20" },
      { internalType: "uint256", name: "score", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes", name: "pubkey", type: "bytes" },
      { internalType: "bytes", name: "custom", type: "bytes" },
      { internalType: "uint8", name: "nLeading0s", type: "uint8" },
      { internalType: "uint8", name: "flag", type: "uint8" },
      { internalType: "uint8", name: "locked", type: "uint8" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "createBounty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "PrivateKey", type: "bytes32" }],
    name: "derivePublicKey",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "bytes32", name: "", type: "bytes32" },
      { internalType: "bytes32", name: "", type: "bytes32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeAddrs",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "feeControl",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_origin", type: "address" }],
    name: "getNonce0Address",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_origin", type: "address" }],
    name: "getNonce0AddressHex",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "pubKey",
    outputs: [{ internalType: "bytes", name: "", type: "bytes" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "addrs", type: "address" },
      { internalType: "uint256", name: "addrT", type: "uint256" },
      { internalType: "bytes", name: "pubK", type: "bytes" },
    ],
    name: "setAddrs",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes", name: "fullKey", type: "bytes" }],
    name: "splitKey",
    outputs: [
      { internalType: "uint256", name: "x", type: "uint256" },
      { internalType: "uint256", name: "y", type: "uint256" },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "bount", type: "uint256" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "tipBounty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes", name: "pubkey", type: "bytes" },
      { internalType: "bytes", name: "pubkey1", type: "bytes" },
      { internalType: "bytes", name: "pubkey2", type: "bytes" },
      { internalType: "uint8", name: "n", type: "uint8" },
      { internalType: "bytes32", name: "PK", type: "bytes32" },
      { internalType: "uint8", name: "flag", type: "uint8" },
    ],
    name: "validate",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes", name: "pubkey", type: "bytes" },
      { internalType: "uint8", name: "flag", type: "uint8" },
    ],
    name: "validatePubkey",
    outputs: [
      { internalType: "address", name: "wallet", type: "address" },
      { internalType: "address", name: "nonce0Addr", type: "address" },
      { internalType: "uint256", name: "score", type: "uint256" },
      { internalType: "bytes20", name: "addrs", type: "bytes20" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "bytes", name: "pubkey", type: "bytes" },
      { internalType: "bytes", name: "pubkey1", type: "bytes" },
      { internalType: "bytes", name: "pubkey2", type: "bytes" },
    ],
    name: "validatePublicKeyAddition",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "bounty", type: "uint256" }],
    name: "withdrawBounty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
